### ISSUE TITLE
Fail to read .yml configuration on startup.

### ISSUE THREAD

**Issue by baardl** [dropwizard/dropwizard-java8#27]
Hi. Hope you are able to help us.
The error
```
applicationapi.yml has an error:
  * Failed to parse configuration at: metrics.reporters; 0 (through reference chain: no.xx.xx["metrics"]->io.dropwizard.metrics.MetricsFactory["reporters"])
```

application.yml
```
metrics:
  reporters:
  - type: datadog
    host: xx.xx.xx.xx
    transport:
      type: http
      apiKey: 12345
```

pom.xml
```
...
<dropwizard.version>1.0.2</dropwizard.version>
		<dropwizard.java8.version>0.9.0-1</dropwizard.java8.version>
		<dropwizard-swagger.version>1.0.0-1</dropwizard-swagger.version>
		<swagger-annotations.version>1.5.4</swagger-annotations.version>
		<logstash-logback-encoder.version>4.7</logstash-logback-encoder.version>
		<dropwizard-logging-logstash.version>1.1-SNAPSHOT</dropwizard-logging-logstash.version>
		<metrics.version>3.1.1</metrics.version>
...
```
